use_frameworks!
#source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

workspace 'AUIVoiceRoomExample'

AlivcSDK='AliVCSDK_ARTC'

target 'Example' do

  pod 'SDWebImage', '~> 5.15.4'
  pod "#{AlivcSDK}", '~> 6.8.0'

  pod "AUIRoomCore/VoiceRoomAPI", :path => '../AUIRoomCore/'
  pod "AUIRoomCore/#{AlivcSDK}", :path => '../AUIRoomCore/'
  pod 'AUIFoundation/All', :path => '../AUIBaseKits/AUIFoundation/'
  pod 'AUIMessage/AliVCIM', :path => '../AUIBaseKits/AUIMessage/'
  pod 'AUIVoiceRoom', :path => '../'
  
end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
               end
          end
   end
end
